name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Create mod folder
        run: |
          mkdir Dight-World
          cp -r bundles content schematics sprites mod.hjson Dight-World/
      
      - name: Archive mod
        run: zip -r Dight-World.zip Dight-World

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: Dight-World.zip
